[package]
name = "plotjuggler"
version = "3.13.2"

[package.build]
backend = { name = "pixi-build-cmake", version = "*" }
source = { path = "../" }

[package.build.config]
# Prefer dynamic linking for zstd and lz4 to use conda-provided libraries
extra-args = ["-DPREFER_DYNAMIC_ZSTD=ON", "-DPREFER_DYNAMIC_LZ4=ON"]

[package.host-dependencies]
qt-main = ">=5.15.15,<6"
lua = ">=5.4.8,<6"
# fmt 12 requires C++20; pin to 11.x to keep the build on C++17.
fmt = ">=11.0.0,<12"
lz4-c = ">=1.9.4,<2"
zstd = ">=1.5.7,<2"
nlohmann_json = "*"
protobuf = ">=4.25.3,<5"
zeromq = ">=4.3.5,<5"
arrow-cpp = ">=13.0.0,<14"
