[package]
name = "plotjuggler"
version = "3.13.2"

[package.build]
backend = { name = "pixi-build-cmake", version = "*" }
source = { path = "../" }

[package.build.config]
# For debugging recipe output and other debug data
debug-dir = "./debug"
# Prefer dynamic linking for zstd and lz4 to use conda-provided libraries
extra-args = ["-DPREFER_DYNAMIC_ZSTD=ON", "-DPREFER_DYNAMIC_LZ4=ON"]

[package.host-dependencies]
qt-main = "*"
lua = "*"
fmt = "*"
lz4-c = "*"
zstd = "*"
nlohmann_json = "*"
protobuf = "*"
zeromq = "*"
arrow-cpp = "*"
