[workspace]
preview = ["pixi-build"]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/robostack-jazzy",  # or robostack-humble, robostack-noetic, etc.
  "https://prefix.dev/conda-forge"
]
platforms = ["linux-64", "osx-arm64", "win-64"]

[workspace.target.win.build-variants]
cxx_compiler = ["vs2022"]

[dependencies]
ros-jazzy-plotjuggler = { path = "./pixi_ros"}

[tasks]
start = "plotjuggler"
