[workspace]
preview = ["pixi-build"]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge"
]
platforms = ["linux-64", "osx-arm64", "win-64"]

[workspace.target.win-64.build-variants]
# We need this to compile on windows correctly
# otherwise it uses a too old stdlib version
cxx_compiler = ["vs2022"]

# ROS2 is our default
[feature.jazzy]
channels = [
  "https://prefix.dev/robostack-jazzy",
]

[feature.jazzy.dependencies]
ros-jazzy-ros-core = "*"
ros-jazzy-plotjuggler = { path = "./pixi_jazzy" }

# No RobotStack Plotjuggler plugin support for win-64
[feature.jazzy.target.unix.dependencies]
ros-jazzy-plotjuggler-ros = ">=2.3.0,<3"

[feature.jazzy.tasks]
start = "ros2 run plotjuggler plotjuggler"

# ROS1 build
[feature.noetic]
channels = [
  "https://prefix.dev/robostack-noetic",  # or robostack-humble, robostack-noetic, etc.
]
# Lets just support linux-64 for now because robostack noetic does not have the plotjuggler
# plugins for the other platforms
platforms = ["linux-64"]

# No RoboStack Plotjuggler plugin support for win-64, osx-arm6
[feature.noetic.target.linux-64.dependencies]
ros-noetic-plotjuggler-ros = ">=2.1.1,<3"

[feature.noetic.dependencies]
ros-noetic-rosbash = "*"
ros-noetic-plotjuggler = { path = "./pixi_noetic" }

[feature.noetic.tasks]
start = "rosrun plotjuggler plotjuggler"

# Environment for non-ROS build
[feature.non-ros.dependencies]
plotjuggler = { path = "./pixi_non_ros" }

# Task to start plotjuggler
[feature.non-ros.tasks]
start = "plotjuggler"

# Environments for both a ros and non-ros build
[environments]
default = ["jazzy"]
noetic = ["noetic"]
non-ros = ["non-ros"]
